### ISSUE TITLE
The database is out of sync

### ISSUE THREAD

**Issue by LinEvil** [Eniripsa96/SkillAPI#118]
Now I have two servers running Skillapi with a same Mysql database,but when a player's data was changed in server A,his data is not be saved in database timely.
So then he join to serverB,there is only the old data can be load for him,the player have to "replay".
Secondly the serverA save the correct data to the database,but the serverB has loaded the wrong data,
then the serverB saves the wrong data to the database and rewrite the correct data.

I guess is the database cache causes this problem,so can you fix it?
You can change the cache for the read only,not the write.

**Comment by Eniripsa96** [comment]
I'm not sure if there's a way to reliably have the SQL database updated in time since it's a connection plus a database write for the SQL versus just a connection for transferring servers. I could potentially add a delay for when a player joins to give more time for the SQL data to go through, but it would cause longer transfer times.

**Comment by Eniripsa96** [comment]
Added a BungeeCord hook in 1.54/1.55. Closing the issue. Feel free to re-open if there's still problems
