### ISSUE TITLE
Flags Help

### ISSUE THREAD

**Issue by Shuboh** [Eniripsa96/SkillAPI#143]
Hey ! I have some question about flags, 
Can flags be on multiple spell, if I toggle a flag, can I use this flag for get actions on another spell ?

**Comment by AngDrew** [comment]
Yes you can

**Comment by Shuboh** [comment]
Oh ! Thx, so i haven't understand yet how to use it :/ can i give you a screen shot of the spells for helps ? (The yml or Dynamic editor if yes ?)

**Comment by AngDrew** [comment]
Ill try my best from my iphone :D

**Comment by AngDrew** [comment]
I have some example

Skill one
Target: single
-flag:(name of the flag) (duration)


Skill two
Target: single
-condition:flag(name of flag)
--damage(10)

So if the target dont have "name of flag" flag then the skill two wont work
Skill one function is set flag to specific target for a duration of time

**Comment by AngDrew** [comment]
Oh yah
That 10 in danage mean the value

I forget a lot of thing in dynamic editor since i dont manage server anymore.. so i write something that i can do from my phone

**Comment by Shuboh** [comment]
Okay thx, so i have other question ^^ : 
My skill one have This : 
Target Self (i let that or i put Single ?)

- Flag: [BlaBla] for 5 Sec

the Skill two have this : 

- Condition [Blabla] set
-- Condition  [Blabla2] not set
--- It do a command execute by the console (from a plugin that i made)
- Condition [Blabla] not set
-- Condition  [Blabla2] set
--- It do a command execute by the console (from a plugin that i made)

and that doesn't works :/

**Comment by Shuboh** [comment]
Some precision about what I want to make : 

I want to make a Rune systeme whene the player can choose some rune (skill) to use and create a rune combo that will create (or at least use) a spell from one single spell so I have

Rune : 
Fire
Water
Air
Earth
Power
Mobility
ect...

and another skill that activate the rune combo named Activate
if that can help

**Comment by AngDrew** [comment]
So its like invoker eh??

**Comment by AngDrew** [comment]
Example i have 3 skill to set the flag and the value

The spell is:
Fire
Lightning
Earth

I have other skill that will handle the value and a lot of skill that will trigger if i have flag combo

Value?
So each skill (earth lightning fire) will add value 1 to self so i can make the max conbo of the skill
So you will need skill with passive and condition
Passive
-condition:value (min amount: 4, max amount: 99)
--value set:value(amount: 0)
--removeflag:(fire)
--removeflag:(lightning)
--removeflag:(earth)
Makesure the skill have 0 cost so the player have it automatically and hidden.. because this is passive handler so the player doesnt need to know about it

The flag skill
Sunstrike
Target:Self
-Condition:flag(fire)
--condition:flag(fire)
---cindition:flag(fire)
----target:single
-----damage(100)

Makesure that the flag all is set. And you can make the duration for the flag and value make them same so it will gone together
And you can make one more skill to reset the combo

If you try the skill:
If you cast fire 3times in a row then sunstrike will be cast
Enemy in front of the caster will be damaged by 100

😀 Hope this help you..

**Comment by AngDrew** [comment]
Oops my bad you should make the value to
Value_fire
Value_lightning
Value_earth
So the sunstrike will be like:
Target:self
-Condition:value(Value_fire, amount:3)
--target:single
---damage(100)

**Comment by AngDrew** [comment]
And the flag is useless :/
Yeah you need value not flag :D

**Comment by AngDrew** [comment]
Btw sorry for my rip english i tried my best to learn it but i got a minimum score 😂

**Comment by Shuboh** [comment]
Np man , I'm not English either ^^, btw Thx for all (the DOTA's invoker was a really good exemple)

so flag systeme is not the best for handle that, K 
Another thing : The 3 Fire condition is usefull ?
because whene i think about it : if it's like coding, it will read lineary and not look about how Many "fire flag" you have nha ?

**Comment by AngDrew** [comment]
Thats why i told you
You should use value instead of flag
So you just need to check the value amount

Because if i have 3x checking for flag it will passed and if i  have 1 fire then the enemy will be damaged :o

**Comment by AngDrew** [comment]
My brain become fool when night lol
I cant focus
In my time this is 1.11 am '-'

**Comment by Shuboh** [comment]
it's only 8:11 PM for me ^^

**Comment by Shuboh** [comment]
and I use the Flag option, because i want to use only 1 type of "rune" for each spell

**Comment by Shuboh** [comment]
but i was thinking, the target type : self is obligatory ?

**Comment by AngDrew** [comment]
Have fun with dynamic editor bro..
I have made a lot of kind skills for my server in past so fun

Is it solved?
You can close the issue :D

**Comment by AngDrew** [comment]
Yes i guess you must use self
Because you target self and check if you have value then will run the children

**Comment by AngDrew** [comment]
The targetting system is started from self by default

If you target single it will target infront of you

Then if the children is target area it will target area of the single that you have targetted

Target:single
-target:area
--damage(1)

This will damaging enemy in front of you and deal area damage

**Comment by Shuboh** [comment]
THX MEN ALL THE SYSTEM WORKS LOVE YOU BRO
