### ISSUE TITLE
Option to not show the Level for citizen npc's

### ISSUE THREAD

**Issue by MWFIAE** [Eniripsa96/SkillAPI#189]
![image](https://user-images.githubusercontent.com/6072971/31444613-f9f32220-ae9c-11e7-9042-05f07f8db72c.png)
Kind of duplicate to the last comment in #102 
Which I'm assuming was just overlooked. 
It doesn't make sense to the player if npc's are showing him a level.

Another option could be to display ??? Level instead of 0 Level.
For my server I would prefer to not show it at all for npcs. But maybe someone would like the ??? option :)

**Comment by MWFIAE** [comment]
We also just realized that it also displays 0 Level for us, which isn't true

**Comment by Eniripsa96** [comment]
The text is set up via scoreboards, which I think just by default has a display for everyone, including NPCs. I've disabled setting up scoreboards for NPCs, but since the players themselves have it set, it appears regardless. Also, I cannot change the 0 to ??? since it is required to be a number due to being a scoreboard.

Closing the issue as I cannot fix this.
