### ISSUE TITLE
New Trigger

### ISSUE THREAD

**Issue by AngDrew** [Eniripsa96/SkillAPI#190]
trigger name: click
options: on right click and on left click

idea: for instant skill like archer can throw bow without pulling the bow

**Comment by Eniripsa96** [comment]
Click combos are kind of there for that. Also, firing the bow early can be done by just looking at launch, cancelling it, and firing a new projectile at the desired speed, such as 3 for normal fire rate.

**Comment by AngDrew** [comment]
hmm
thats not working..

**Comment by Eniripsa96** [comment]
What isn't, using the launch trigger?

**Comment by AngDrew** [comment]
I cant cancel the launch event it launch my arrow from bow

**Comment by Eniripsa96** [comment]
Did you add the projectile mechanic along with the Cancel as recommended? If so, then yeah, it would still fire an arrow since  you added the projectile mechanic.

**Comment by AngDrew** [comment]
sorry for late reply
its working but its not efetive because i cant add the delay or attack speed

**Comment by Eniripsa96** [comment]
When using the launch trigger, it provides "api-velocity" as a value. Toss that in as the projectile's speed, and you're good to go.

**Comment by AngDrew** [comment]
Whats the difference between skill with launch and projectile with speed apo-velocity and when i pull my bow

My target is when i right click/pulling bow
Cancel event
Launch
Add some delay to the skill

Btw, can i disable cooldown msg?

One  ore thing how i spread inventory between player class account?
So i have diferrence inven on my Knight and on my Archer

And can you add more skript options? So i can access almost every thing skill api with skript addon (skrpg)

**Comment by AngDrew** [comment]
Sry for my rip english
I cant think correctly when 12am or up

**Comment by Eniripsa96** [comment]
Not sure what you're asking about the difference between. 
Launch trigger + Projectile mechanic + api-velocity is all for the same thing

You can disable the cooldown message by making it an empty in language.yml

There's not a feature for unique inventories per account yet.

skript likely has command options, in which case, most SkillAPI functionality should already be available.

Closing the issue due to age. Feel free to re-open in case you think something was missed.
