### ISSUE TITLE
Particle Projectile not applying child components.

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#214]
`Trigger: Cast`
  `Target: Cone`
    `Mechanic: Particle Projectile > Rain`
      `Mechanic: Damage`
      `Mechanic: Speed`
So I have a skill like that but it's not applying child components upon landing. It should deal dmg when particles drop and set their speed to 0.5.

**Comment by AngDrew** [comment]
Really??
But its working fine for me..
But im not using rain..

**Comment by Eniripsa96** [comment]
Couple of notes:
1) Speed needs to be negative for projectiles to rain downward (e.g. -0.5)
2) Since "Rain" is AOE, you generally do not need an AOE target before it (Cone)

Will resolve since those two considerations should take care of your issue. If you're still having problems, feel free to re-open the issue.
