### ISSUE TITLE
Class Skill GUI improperly displaying Names/Lore

### ISSUE THREAD

**Issue by Insilvon** [Eniripsa96/SkillAPI#218]
Hello there, 
I've hit a snag when players use multiple classes. 
They type /class skill in order to view their active classes via the GUI menu. Issue is that none of the "items" display a class name nor class lore, even though both are defined in the .yml. I dug through the Spigot discussion page and searched through this github issue tracker and couldn't find anyone with similar issues, so I'm assuming it's something I probably did wrong, but I've been using the dynamic editor so I'm not entirely sure what's up. 

I'm currently on Spigot 1.12.1, running your current (v3.103) SkillAPI and MCCore 1.6.4. 

Any information on potential fixes would be greatly appreciated!

**Comment by AngDrew** [comment]
Have you try to restart server instead of reloading it?
Never use reload command because it ruins everything...

If you change skillapi yml file you can use reload cmd instead of restarting 😂

I have no idea if this not work maybe you can try something lile change item type
Change name of the group or class or re create your skillapi dynamic (backup the old one first is recomended before you regrets :3)

**Comment by Insilvon** [comment]
I attempted a server restart multiple time.
When I first loaded the new stuff, I started with a ./class reload. The names were showing correctly, but without lore or colored name. 
I restarted and all fields were gone. 
I removed and re-uploaded the new stuff while server was down. Still broken when I turned the server back on.

**Comment by AngDrew** [comment]
Delete skill api folder and try to make 1 example class and see if it show or not
I have the same issue before bur i forgot how to solve it

**Comment by Insilvon** [comment]
[bump]

**Comment by Eniripsa96** [comment]
Closing due to age of the issue. If still having the issue, feel free to re-open, just provide a config file of a class that isn't showing up in the menu.
