### ISSUE TITLE
Skillapi with anti-cheat plugin

### ISSUE THREAD

**Issue by TLeung094** [Eniripsa96/SkillAPI#256]
any anti-cheat can compare with skillapi?
I used the AAC is cannot compare 
The AAC will warning like used cheat when I using Skillapi skill

**Comment by Eniripsa96** [comment]
I've heard of NoCheatPlus being used with SkillAPI, not sure if they had to disable various features though. I don't know enough myself to be of too much assistance. Try searching or asking around Spigot for plugins that work with other skill plugins as well, since those likely behave in a similar fashion.
