### ISSUE TITLE
Damage Skill - Deal % of the melee attack.

### ISSUE THREAD

**Issue by TerraPrimal** [Eniripsa96/SkillAPI#258]
Greetings, if this isn't already something in the premium version (and I have over looked it) could you consider adding it.

I want to be able to deal % damage based on what the melee attack would do, for example if my melee attack would have done 100 damage, setting damage to 200% would deal 200 damage.

This would allow skill damage to scale based on what items a player has rather then the flat damage on damage based on the targets HP.

Thanks.

**Comment by Zicerite** [comment]
There is a way with the "Damage Lore" mechanic, which stores a value from your weapon's lore, and you can multiply it, and turn it into damage. Example below

[Flame Wheel.zip](https://github.com/Eniripsa96/SkillAPI/files/1953280/Flame.Wheel.zip)

**Comment by TerraPrimal** [comment]
Thank you for the help Zicerite,

I'm sure this will help in the mean time, but unfortunately it's not quite the same as needed as it doesn't take into effect potion effects and other effects (such as crit or damage range on weapons (Damage: 10-20)).
I kinda need a damage option that takes the getFinalDamage() and multiplies it or w/e would be the best way.

Once again, thank you. Your idea was much appreciated.

**Comment by Eniripsa96** [comment]
Since plugins can modify weapon damage in numerous ways, it's hard to grab a final damage of an attack without it actually happening.

If you're okay with requiring the user to hit something, the "Physical Damage" trigger provides the damage dealt as a value. You can use that value and multiply it or use it in other triggers to compute your damage.

See https://github.com/Eniripsa96/SkillAPI/wiki/_Trigger-Physical-Damage#details

**Comment by Eniripsa96** [comment]
Closing since the above should take care of the use case. Feel free to re-open if you think something else is needed.
