### ISSUE TITLE
Chat prefix not work

### ISSUE THREAD

**Issue by SnUncle** [Eniripsa96/SkillAPI#299]
Im using the lastest premium skillapi and i enable it in config
but if but if i do not set scoreboard-enabled: 'true' the prefix won't show at all

**Comment by SnUncle** [comment]
And when i reset my class the prefix won't dispear

**Comment by Eniripsa96** [comment]
Replied in discord, but prefixes weren't intended to function when scoreboards are disabled since they operate through scoreboards. If using other display plugins, you may just want to use the placeholders provided by SkillAPI to customize your name through other plugins.

Relevant PlaceholderAPI placholders:
- %prefix%
- %prefix_<group>%
