### ISSUE TITLE
Feature Request - Skills dealing physical damage

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#322]
I want to make some classes like warrior, rogue deal physical damage with skills. Its hard to balance skill and physical defenses for me. Like I cant tell the difference warrior and mage.

**Comment by Eniripsa96** [comment]
Copy + Paste from discord:
"Physical Damage" for skills is a little strange for skills since other plugins may  need to handle damage dealt by SkillAPI in a special way (e.g. bypasses for no-cheat plugins, other people reading damage being done, etc.). I could possibly just change which internal event is launched (PhysicalDamageEvent vs SkillDamageEvent). I forget if buffs work off of those events, I'd have to double check, but if they do, it may be possible. I wouldn't make it work in the same way as a normal physical attack though."

**Comment by RacerN2O** [comment]
I'm all for a way to have more real physical damage with skills as well. It would be great for triggering Physical Damage triggers etc.

**Comment by Lix3nn53** [comment]
Can you add a physical damage option like a classifier but skill-damage and skill-defense attributes doesnt effect?

**Comment by Eniripsa96** [comment]
Added in 1.87
