### ISSUE TITLE
Request: Improved Push

### ISSUE THREAD

**Issue by RacerN2O** [Eniripsa96/SkillAPI#340]
It would be great if we could push relative to remembered targets, as opposed to the caster only.
An option for push to work vertically just as it does horizontally would be great as well. From what I've experienced push currently seems to have a fixed upwards momentum, essentially making it a launch with less options.

**Comment by Eniripsa96** [comment]
The vertical speed isn't fixed, but it is dampened due to vertical velocity being much stronger than horizontal velocity (speed 1 upwards sends you a lot higher than speed 1 sideways). The actual formula used is:

verticalVelocity = y / 5 + 0.5

Where y just comes from the distance between the target and the source. If you push something directly over your head, it still should push them vertically. Higher speeds will also make them be pushed farther vertically.

If you want a stronger vertical speed, you can use both push and launch.

**Comment by RacerN2O** [comment]
Alright, I remember running into an issue with lots of consecutive pushes (or pulls, rather) launching enemies into the air above myself instead of them getting stuck at the players position.

I'll try recreating that scenario soon.

**Comment by Eniripsa96** [comment]
Added in 1.81
