### ISSUE TITLE
[Question/Bug] Values turning "none"

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#344]
I wanted to ask if there was a reason why values randomly turn into "none" after a long time (ie. being idle for awhile), or after teleporting a lot.
I Mainly get this to trigger when using warps via EssentialsX though.

![2018-07-26_07 44 33](https://user-images.githubusercontent.com/30883277/43269601-0a384834-90a8-11e8-8296-6029c1b93b88.png)

**Comment by Eniripsa96** [comment]
The times values are cleared are:
- Death
- Chunk Unload (to entities in the chunk)
- Log out

I'm wondering if teleporting out of a chunk unloads the chunk before it removes the player entity out of it. If that's the case, I'll have to exclude players from the unload functionality. As for being idle, I'm not sure, unless the server also "unloads" the chunk due to inactivity and reloads when you start moving again, but that's doubtful.

**Comment by Zicerite** [comment]
Its pretty bizzare, all of my testers have gotten it by sitting idle (like, being afk for long periods of time).
It definatly happens through teleporting though. 
Thx

**Comment by Eniripsa96** [comment]
1.85 patches the only thing I think could cause this, so let me know if you continue experiencing this issue. Will close for now, but feel free to re-open if it keeps on happening.
