### ISSUE TITLE
[Bug?] Issues with allies between Vanilla Scoreboard teams

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#406]
I was making a system for my team pvp setup, and i was using vanilla's scoreboard's team system. In doing so, i found some issues with it.

While allies can't hurt each other with each other's skills, which is expected, some other stuff doesn't work that way.

1. Allies can still cause Launch/Push to each other.
2. Allies can affect each other with negative potion effects/Negative status effects (Ie. Poison, Stun)
3. Allies can burn each other from the Fire Mechanic.

What I would like is a way that, if the target of for example, Area Target that affects Enemies, would ignore players that are in the same team as the player, as well as Targets that target allies affecting players that are on the same team as the player.
And Both affecting both of course.

**Comment by Eniripsa96** [comment]
Allies via scoreboards isn't really supported quite yet, which is why you would see effects applying to them. The damage might not show up for some reason that works outside of the normal damage events in MC/Spigot code. I'll treat this as an enhancement to add the functionality since it wasn't intended and resolve this issue in favor of #387 since that was posted first.
